version: "3.8"

services:
  db:
    image: postgres:15rc1-alpine3.16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - database/postgres-credentials.env
    volumes:
      - $PWD/database/database-volume:/var/lib/postgresql/data
    networks:
      - application
  application:
    container_name: where-is-my-pet
    command: [ "--sslport", "8181" ]
    ports:
      - "4848:4848" # HTTPS admin listener
      - "8080:8080" # HTTP listener
      - "1607:8181" # HTTPS listener
      - "9009:9009" # Debug port
    build: .
    networks:
      - application
    depends_on:
      - db

networks:
  application: