apiVersion: v1
kind: Service
metadata:
  name: pet-service
spec:
  selector:
    app: pet-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-deployment
spec:
  selector:
    matchLabels:
      app: pet-app
  replicas: 2
  template:
    metadata:
      labels:
        app: pet-app
    spec:
      containers:
        - name: pet-app
          image: repo/where-is-my-pet-application:1
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pet-volume
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 60
      volumes:
        - name: my-volume

# https://dev.to/amarpreetbhatia/kubernetes-for-java-developers-a-step-by-step-guide-to-containerizing-your-applications-2hko